### ISSUE TITLE
unrelated

### ISSUE THREAD

**Issue by bucanero** [shagkur/irrlichtPS3#1]
hello @shagkur ,

totally unrelated to this repo, but just wanted to check if you were able to update/downgrade your PS3 firmware or if you had any issue?
Since you've been adding stuff to PSL1GHT I assumed everything worked fine, 😄  but if you had any issue let me know

cheers

**Comment by shagkur** [comment]
Hey @bucanero 
thanks for asking. Yes, the downgrade and the following upgrade to rebug worked like a charm for me. 
Otherwise, as you realized, i wouldn't have added stuff to PSL1GHT

cheers

**Comment by bucanero** [comment]
😄 good to hear! 
btw, (probably not needed since you're on DEX), I've updated/ported the PS3LoadX host app to the latest psl1ght + tiny3D to send .self's over the network:
https://github.com/bucanero/ps3loadx

have a nice week, cheers!
